describe("Testing our form", function ()
{
  beforeEach(function ()
  {
    cy.visit("http://localhost:3000")
  })
  it("Add test to inputs and submit form", function ()
  {
    cy.get('[for="name"] > input')
      .type("Jessica Rabbit")
      .should("have.value", "Jessica Rabbit")
    cy.get('input:invalid').should('have.length', 0)
    cy.get('[for="email"] > input')
      .type("Jessica@Rabbits.com")
      .should("have.value", "Jessica@Rabbits.com")
    cy.get('[for="Password"] > input')
      .type("1234")
      .should("have.value", "1234")
    cy.get('[for="agreement"] > input')
      .check()
      .should('be.checked')
    cy.get('button')
      .click()
  })
  it('check validation message on invalid input', () =>
  {
    cy.get('[for="name"] > input')
      .type("Jessica Rabbit")
      .clear()
    cy.get('[for="name"] > .error')
      .should('have.length', 1)
      .contains('Name is a required field bro.')

    cy.get('[for="email"] > input')
      .type("Jessica")
    cy.get('[for="email"] > .error')
      .contains('Must be a valid Email Address.')
    cy.get('[for="email"] > input')
      .clear()
    cy.get('[for="email"] > .error')
      .contains('Must include an email address')
      
      cy.get('[for="Password"] > input')
      .type('a')
      .clear()
      cy.get('[for="Password"] > .error')
      .contains('Must choose a password')

  })
})
